name: kirkit
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  random_string: ^2.1.0
  firebase_core: ^0.5.0+1
  image_picker: ^0.6.7+12
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true


